# Generated by Django 4.0.1 on 2023-04-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardparticipant',
            options={'verbose_name': 'частник', 'verbose_name_plural': 'Участники'},
        ),
    ]
