# Generated by Django 4.0.1 on 2023-04-04 14:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Укажите номер телефона', max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
